# Administrador
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Duarte Lacerda', 'duartelacerda4@gmail.com', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'A');
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Vanessa Ramalho', 'vanessa310804@gmail.com', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'A');
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Daniel Cochiço', 'danielcochico39@gmail.com', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'A');
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Daniel Ribeiro', 'danielribeiro290404@hotmail.com', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'A');
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Paulo Leal', 'pauloandeleal@gmail.com', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'A');

# Clientes
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Hugo Soares', '2221019@my.ipleiria.pt', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'N');
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Pedro Rodrigues', '2221031@my.ipleiria.pt', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'N');
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Martim Conceição', '2221003@my.ipleiria.pt', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'N');
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Carlota Gouveia', '2220997@my.ipleiria.pt', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'N');
INSERT INTO users (name, email, email_verified_at, password, created_at, updated_at, role)
VALUES ('Margarida Simões', '2221009@my.ipleiria.pt', '2023-12-11 17:21:25', '$2y$12$/HIRxktjEiJNElVnX6OD8e1ZN5o8WtXoOv5mBFOtG10.TVPaS/rWK', '2023-12-11 17:20:51', '2023-12-11 17:21:25', 'N');

#Eventos
INSERT INTO eventos (id, nome, descricao, local, data_inicio, data_fim, user_id, deleted_at, created_at, updated_at) VALUES
(1, 'Semana do Camões', 'Nesta semana, o livro principal vai ser "Os Lusíadas" de Luís de Camões, lançado em 1572 e o incentivo vai ser para ler este livro para depois discutirmos de forma ordenada para tirar uma boa conclusão sobre o mesmo e para adquirir uma boa quantidade de conhecimento.', 'Leiria, Rua de Leiria, 2400-181', '2023-12-01', '2023-12-31', 1, NULL, NULL, NULL),
(2, 'Teste', 'Teste', 'Teste', '2023-12-06', '2023-12-31', 1, NULL, NULL, NULL),
(3, 'Teste3', 'Teste3', 'Teste3', '2023-12-01', '2023-12-31', 1, NULL, NULL, NULL),
(4, 'Teste4', 'Teste4', 'Teste4', '2023-12-01', '2023-12-31', 1, NULL, NULL, NULL),
(5, 'Teste5', 'Teste5', 'Teste5', '2023-12-01', '2023-12-31', 1, NULL, NULL, NULL),
(6, 'Teste final', 'Teste final', 'Teste Final', '2023-12-01', '2023-12-31', 1, NULL, NULL, NULL),
(7, 'Teste proximo', 'Teste', 'teste', '2023-12-06', '2023-12-31', 1, NULL, NULL, NULL),
(8, 'Antigo', 'Antigo', 'Antigo', '2023-11-01', '2023-11-23', 1, NULL, NULL, NULL),
(9, 'Antigo 2', 'Antigo 2', 'Antigo 2', '2023-11-07', '2023-12-19', 1, NULL, NULL, NULL),
(10, 'Futuro', 'Futuro', 'Futuro', '2023-12-28', '2023-12-31', 1, NULL, NULL, NULL),
(11, 'Futuro 2', 'Futuro 2', 'Futuro 2', '2023-11-07', '2023-12-19', 1, NULL, NULL, NULL);
INSERT INTO eventos_fotos (id, titulo, foto, ordem, evento_id,  created_at, updated_at) VALUES
(1, 'Imagem que aparece na 1ª ordem na Semana do Camões', 'camoes.jpg', 1, 1,  NULL, NULL),
(2, 'Teste', 'camoes2.jpg', 1, 2, NULL, NULL),
(3, 'Teste3', 'camoes3.jpg', 1, 3, NULL, NULL),
(4, 'Teste4', 'camoes4.jpg', 1, 4, NULL, NULL),
(6, 'Imagem que aparece na 2ª ordem na Semana do Camões', 'camoes2.jpg', 2, 1, NULL, NULL),
(7, 'Imagem que aparece na 3ª ordem na Semana do Camões', 'camoes3.jpg', 3, 1, NULL, NULL),
(8, 'Imagem que aparece na 4ª ordem na Semana do Camões', 'camoes4.jpg', 4, 1, NULL, NULL);

#Livros
INSERT INTO `livros` (`id`, `titulo`, `descricao`, `autor`, `foto`, `edicao`, `user_id`, `deleted_at`, `created_at`, `updated_at`) VALUES
(NULL, 'O Segredo de Espinosa', 'Amesterdão, 1640.\r\n\r\nUm judeu é excomungado na Sinagoga Portuguesa por questionar as Sagradas Escrituras. Uma criança assiste a tudo. O pequeno Bento de Espinosa é considerado o maior prodígio da comunidade portuguesa de Amesterdão, mas o episódio planta nele a semente da dúvida: E se a Bíblia estiver mesmo errada? A suspeita irá lançar Bento na maior busca intelectual de sempre. Quem realmente escreveu os textos sagrados? Qual é a verdade sobre Deus? O que é afinal a natureza? Mas esta é uma busca proibida e depressa o jovem judeu português descobre que terá de pagar um preço terrível pelas suas perguntas. Os rabinos judeus e os pregadores cristãos perseguem-no e acusam-no do pior dos crimes: Heresia\r\n\r\nO Segredo de Espinosa é uma aventura extraordinária, onde acompanhamos a vida de Bento de Espinosa, o maior filósofo português, e a sua busca proibida e perigosa por respostas. E se a Bíblia estiver mesmo errada? O que é a natureza? Quem escreveu os textos sagrados? Estas respostas têm um preço elevado. Acusado de heresia, expulso da Sinagoga Portuguesa em Amesterdão, Bento de Espinosa é perseguido até ao fim dos seus dias.\r\n\r\nNovo romance de José Rodrigues dos Santos, o escritor favorito dos portugueses. Inspirando-se na vida de Bento de Espinosa, considerado o maior filósofo português de sempre, e o inventor do mundo moderno. Uma aventura épica em busca de um segredo...', 'José Rodrigues dos Santos', 'O Segredo de Espinosa.webp', 'Planeta, outubro de 2023', '1', NULL, NULL, NULL),
(NULL, 'A Criada', 'Por trás de cada porta, ela consegue ver tudo.\r\n\r\n«Bem-vinda à família», diz Nina Winchester enquanto me cumprimenta com a sua mão elegante e bem cuidada. Sorrio educadamente e olho para o longo corredor de mármore.\r\n\r\nEste emprego caiu-me do céu. Talvez seja a minha última oportunidade para mudar de vida. E o melhor de tudo é que aqui ninguém sabe nada acerca do meu passado. Posso esconder-me e fingir ser aquilo que eu quiser. Infelizmente, não tardo a descobrir que os segredos dos Winchester são muito mais perigosos do que os meus…\r\n\r\nTodos os dias limpo a bela casa dos Winchester de cima a baixo, vou buscar a filha deles à escola e cozinho uma deliciosa refeição para toda a família antes de subir e comer sozinha no meu quarto minúsculo no sótão.\r\n\r\nTento ignorar a forma como Nina gera o caos só para me ver limpar. Como conta histórias inverosímeis sobre a filha. E como o seu marido, Andrew, parece cada dia mais destroçado. Quando o vejo, e àqueles belos olhos castanhos tão tristes, é difícil não me imaginar no lugar de Nina. Com o marido perfeito, a roupa chique, o carro de luxo. Um dia, experimentei um dos seus vestidos só para ver como me ficava. Mas ela percebeu... e foi aí que descobri porque é que a porta do meu quarto só trancava pelo lado de fora...\r\n\r\nSe sair desta casa, será algemada.\r\nDevia ter fugido enquanto podia. Agora, a minha oportunidade desapareceu. Agora que os polícias estão na casa e descobriram o que está no andar de cima, não há volta atrás.\r\nEstão a cerca de cinco segundos de me ler os direitos. Não sei muito bem porque não o fizeram ainda. Talvez esperem induzir-me a dizer-lhes algo que não devia.\r\nBoa sorte com isso.\r\n\r\nO polícia com o cabelo preto raiado de grisalho está sentado ao meu lado no sofá. Muda a posição do seu corpo entroncado sobre o cabedal italiano cor de caramelo queimado. Pergunto-me que tipo de sofá terá em casa. Não um, certamente, com um preço de cinco dígitos como este. Provavelmente de uma cor foleira como laranja, coberto de pelo de animais de estimação e com mais do que um rasgão nas costuras. Pergunto-me se estará a pensar no seu sofá em casa e a desejar ter um como este. Ou, mais provavelmente, está a pensar no cadáver lá em cima no sótão.', 'Freida McFadden', 'A Criada.webp', 'Alma dos Livros, junho de 2023', '1', NULL, NULL, NULL),
(NULL, 'Pai Rico, Pai Pobre', 'O livro de finanças pessoais mais vendido de sempre!\r\nEdição revista e atualizada - inclui 9 secções de estudo\r\nO clássico das finanças pessoais que se mantém atual\r\n\r\nDesfaz o mito de que precisa de ter um salário elevado para enriquecer - especialmente num mundo onde a tecnologia, os robôs e a economia global estão a mudar as regras.\r\n\r\nEnsina porque adquirir e criar ativos pode ser mais importante para o seu futuro do que um grande salário.\r\n\r\nDesafia a crença de que a sua casa é um ativo - como milhões de pessoas aprenderam quando a bolha imobiliária rebentou.\r\n\r\nRecorda-nos porque não podemos depender do sistema escolar para ensinar os nossos filhos sobre dinheiro - e por que razão essa competência fundamental para a vida é mais importante hoje do que nunca.\r\n\r\nExplica o que deve ensinar aos seus filhos sobre dinheiro - para que possam estar preparados para os desafios e oportunidades do mundo de hoje e desfrutar da vida rica que merecem.', 'Robert T. Kiyosaki', 'Pai Rico, Pai Pobre.webp', 'Vogais, novembro de 2023', '1', NULL, NULL, NULL),
(NULL, 'Tudo Foi Como Tinha de Ser', 'Quando um vídeo íntimo é partilhado nas redes sociais, Mariana sente o seu mundo desmoronar. Incapaz de lidar com o julgamento dos outros, congela a matrícula na faculdade e fecha-se em casa, o único sítio onde se sente segura.\r\n\r\nGonçalo prepara-se para realizar o sonho de abrir um restaurante. Por um acaso do destino, o sítio ideal surge na rua onde vive Mariana. Quando percebe a prisão em que ela vive, começa a lançar-lhe desafios para a ajudar a vencer os seus medos. A paixão acaba por surgir. Mas conseguirá Gonçalo ajudá-la a enfrentar os seus problemas? Ou tornar-se-á no maior deles?\r\n\r\nÀs vezes, temos tanto receio de ser criticados que ficamos reféns da opinião dos outros. Acabamos a fazer o que nos dizem ser melhor para nós, ou simplesmente escondemo-nos do mundo.\r\n\r\nNeste romance emocionante, Raul Minh’alma, um dos autores mais vendidos dos últimos anos, mostra-nos o caminho para deixarmos de viver com medo do que os outros pensam sobre nós.', 'Raul Minh\'alma', 'Tudo Foi Como Tinha de Ser.webp', 'Manuscrito Editora, novembro de 2023', '1', NULL, NULL, NULL),
(NULL, 'Olhem para o Mundo com o Coração', 'Num testemunho intenso e emotivo, o médico Gustavo Carona conta-nos neste livro as suas missões humanitárias em países devastados pela guerra, pela pobreza extrema e pelo total abandono. Olhem para o Mundo com o Coração é simultaneamente um grito de alerta contra a indiferença, uma reflexão sobre um planeta profundamente desigual e um testemunho, tão comovente quanto admirável, que nos mostra como o lado mais altruísta do ser humano combate no terreno, sob condições a todos os níveis adversas, a sua faceta mais sombria e cruel.\r\n\r\nUma homenagem sentida aos homens e mulheres que, todos os dias e um pouco por todo o globo, salvam vidas condenadas à morte e atenuam o sofrimento das vítimas mais desprotegidas, mantendo assim acesa a chama da esperança num mundo melhor.', 'Gustavo Carona', 'Olhem para o Mundo com o Coração.webp', 'Oficina do Livro, outubro de 2023', '1', NULL, NULL, NULL),
(NULL, 'Heartstopper Volume 5', 'The phenomenally popular graphic novel series returns with Nick and Charlie very much in love but Nick\'s planned move to university hanging over their lasting future.\r\n\r\nBoy meets boy. Boys become friends. Boys fall in love. The bestselling LGBTQ+ graphic novel about life, love, and everything that happens in between: this is the fifth volume of the Heartstopper series.\r\n\r\nNick and Charlie are very much in love. They\'ve finally said those three little words, and Charlie has almost persuaded his mum to let him sleep over at Nick\'s house ... But with Nick going off to university next year, is everything about to change?\r\n\r\nBy Alice Oseman, winner of the YA Book Prize, Heartstopper encompasses all the small moments of Nick and Charlie\'s lives that together make up something larger, which speaks to all of us.\r\n\r\nContains discussions around mental health and eating disorders, and sexual references.', 'Alice Oseman', 'Heartstopper Volume 5.webp', 'Hachette Children\'s Group, dezembro de 2023', '1', NULL, NULL, NULL);

#Categorias
INSERT INTO `categorias` (`id`, `nome`, `descricao`, `created_at`, `updated_at`) VALUES
(NULL, 'Romance', 'O termo romance pode referir-se a dois gêneros literários. O primeiro deles é uma composição poética popular, histórica ou lírica, transmitida pela tradição oral, sendo geralmente de autor anônimo; corresponde aproximadamente à balada medieval. Como forma literária moderna, o termo designa uma composição em prosa.', NULL, NULL),
(NULL, 'Thriller', 'Thriller, tríler ou suspense é um gênero da literatura, filmes, jogos eletrônicos e televisão que usa o suspense, tensão e excitação como principais elementos do gênero. Um exemplo de thrillers são os filmes de Alfred Hitchcock.', NULL, NULL),
(NULL, 'Aventura', 'O género literário e cinematográfico de aventura caracteriza-se por narrativas emocionantes e estimulantes, frequentemente centradas em personagens que enfrentam desafios extraordinários em busca de conquistas significativas. Elementos-chave deste género incluem viagens emocionantes, perigos iminentes, descobertas surpreendentes e o desenvolvimento do protagonista ao longo da jornada.', NULL, NULL);

#Livro_Categorias
INSERT INTO `livros_categorias` (`id`, `livro_id`, `categoria_id`, `created_at`, `updated_at`) VALUES (NULL, '1', '1', NULL, NULL), (NULL, '2', '2', NULL, NULL), (NULL, '4', '1', NULL, NULL);

#Faqs
Insert INTO `faqs` (`id`, `question`, `answer`, `approved`, `created_at`, `updated_at`) VALUES
(NULL, 'Que eventos é que a Leiribook promove regularmente?', 'Organizamos uma variedade de eventos, incluindo discussões de livros, palestras com autores, e clubes do livro. Consulte o nosso calendário de eventos para obter informações atualizadas.', 1, NULL, NULL),
(NULL, 'Como é que posso participar em eventos da Leiribook?', 'Para participar dos eventos, basta verificar o calendário no nosso site e seguir as instruções de inscrição ou comparecer aos eventos abertos.', 1, NULL, NULL),
(NULL, 'Como posso sugerir um livro para a leitura em grupo?', 'Aceitamos sugestões de leitura. Envie as suas recomendações para leirbook.contact@gmail.com ou através do formulário de contato no nosso site.', 1, NULL, NULL),
(NULL, 'Posso doar livros à associação? Como proceder?', 'Sim, aceitamos doações de livros. Entre em contato connosco através do formulário de contacto para obter mais informações.', 1, NULL, NULL),
(NULL, 'Qual é a política de privacidade da Leiribook em relação aos dados dos membros?', 'Respeitamos a privacidade dos nossos membros. Consulte as nossas políticas de privacidade para obter informações detalhadas sobre como tratamos e protegemos os dados pessoais.', 1, NULL, NULL),
(NULL, 'Como é que posso entrar em contato com a equipa da Leiribook em caso de dúvidas ou preocupações?', 'Você pode entrar em contato conosco através do formulário de contacto em nosso site. Estamos aqui para ajudar!', 1, NULL, NULL),
(NULL, 'Posso sugerir tópicos ou autores para futuros eventos ou discussões?', 'Sim, encorajamos sugestões de membros. Envie as suas ideias para leiribook.contact@gmail.com ou através do formulário de contacto.', 1, NULL, NULL);